"""Dades del calendari del mòdul 5104 (font única).

Executa `python tools/genera.py` per regenerar el calendari, els índexs de
professorat i les fitxes de sessió que encara són plantilla.
"""

W = "https://alapvi.github.io/sbd/"

# (fitxer, data ISO, prof, títol, RA/CA, continguts, pràctica, web[(títol, ruta)], aules[noms], nou[str], estat)
# estat: "redactada" = teoria escrita a mà (no es regenera) · "plantilla" = fitxa generada
P1 = [
    ("s01-tipus-dades", "2026-10-05", "Tipus de dades i fonts", ["RA1 a", "RA1 b"],
     "Presentació del mòdul. Tipus de dades segons l'origen, la naturalesa i la formalitat. Ubicació local o al núvol i distribució física.",
     "Fitxa de classificació de fonts reals.",
     [("Introducción a BI · Visión general", "ingenieria-datos/ud1-introduccion/"), ("Tipos de datos", "ingenieria-datos/ud1-introduccion/tipos-de-datos/")],
     ["Tipus de dades.pdf", "Mentimeter i infografia BI"], [], "redactada"),
    ("s02-gestors-formats", "2026-10-19", "Gestors i formats", ["RA1 c", "RA1 d", "RA1 e", "RA1 f"],
     "Fonts no estructurades i web semàntica (descriptiu). SGBD SQL i NoSQL. Formats d'intercanvi. Dades SCADA/IoT.",
     "Un mateix conjunt de dades en CSV, JSON i XML.",
     [("NoSQL", "nosql/nosql/"), ("Modelos de datos", "nosql/moddatos/")],
     ["Presentacio_Intro_noSQL.pptx"], [], "redactada"),
    ("s03-entorns-arquitectures", "2026-10-26", "Entorns i arquitectures", ["RA1 g", "RA1 h", "RA3 c"],
     "On-premise i núvol. Staging, ODS, DW, data mart i arquitectura medallion. SMP, MPP i data locality. OLTP vs OLAP.",
     "Quadre comparatiu d'arquitectures.",
     [("Tipos de entornos y arquitectura de datos", "ingenieria-datos/tipos-entornos-arquitecturas/"), ("Big Data", "ingenieria-datos/bigdata/"), ("Ingeniería de datos", "ingenieria-datos/ingenieria-datos/")],
     ["Entorns i model de dades.pdf", "1.1 Introducció a Big Data.pptx"], [], "redactada"),
    ("s04-model-multidimensional", "2026-11-02", "Model multidimensional", ["RA3 c"],
     "Prova curta del RA1. Procés de negoci, grànul, fets, mesures, dimensions i claus subrogades.",
     "Disseny en paper del model de compres.",
     [("Modelos multidimensionales", "ingenieria-datos/modelos-multidimensionales/")],
     ["Exercici_ Model Multidimensional Compres.docx"], [], "redactada"),
    ("s05-practica-ddl", "2026-11-09", "Pràctica: OLTP i DDL", ["RA3 a"],
     "Muntar l'OLTP de compres i crear l'estrella dw_compras amb DDL.", "Pràctica OLTP→OLAP, part 1.",
     [], [], [], "redactada"),
    ("s06-practica-carrega", "2026-11-16", "Pràctica: càrrega del DW", ["RA3 b", "RA3 d"],
     "Càrrega de dimensions, validació de lookups, càrrega del fet i reconciliació.", "Pràctica OLTP→OLAP, part 2.",
     [], [], [], "redactada"),
    ("s07-practica-scd-dcl", "2026-11-23", "Pràctica: SCD1 i DCL", ["RA3 b", "RA3 e"],
     "MERGE i SCD tipus 1. Rols, permisos i Row Level Security.", "Pràctica OLTP→OLAP, part 3.",
     [], ["PostgreSQL per a Big Data.docx"], [], "redactada"),
    ("s08-practica-copy", "2026-11-30", "Pràctica: càrrega massiva", ["RA3 f", "RA2 c"],
     "Escalat a 100.000 línies. COPY i \\copy davant d'INSERT. SQL embegut en Python.", "Pràctica OLTP→OLAP, part 4.",
     [], [], [], "redactada"),
    ("s09-practica-benchmark", "2026-12-14", "Pràctica: benchmark i paral·lelisme", ["RA2 d", "RA2 e", "RA3 g"],
     "Filtres en origen, JOINs i EXPLAIN. Taula particionada i càrrega paral·lela. Lliurament del RA3.", "Pràctica OLTP→OLAP, part 5.",
     [], [], [], "redactada"),
    ("s10-mongodb-1", "2026-12-21", "MongoDB I", ["RA4 a", "RA4 b", "RA4 c", "RA5 b"],
     "MongoDB local i a Atlas (núvol). Accés amb mongosh, Compass i pymongo.",
     "Connexió local i al núvol, i consultes find amb filtres i projeccions.",
     [("Introducción a MongoDB", "mongodb/intromongo/"), ("MongoDB", "mongodb/mongodb/"), ("Instalación", "mongodb/instalacion/"), ("Primeros pasos", "mongodb/basicsmongo/")],
     ["MongoDB.pptx", "Presentacio_Intro_noSQL.pptx"], [], "plantilla"),
    ("s11-mongodb-2", "2027-01-11", "MongoDB II", ["RA4 d", "RA5 c", "RA5 d"],
     "CRUD, aggregation pipeline, validació d'esquema, índexs i càrrega massiva (insertMany, bulkWrite, mongoimport).",
     "Carregar un dataset i fer consultes d'agregació.",
     [("Operaciones CRUD", "mongodb/mongodbcrud/"), ("Consulta de datos", "mongodb/mongodbdatos/"), ("Diseño de modelado", "mongodb/modelado/")],
     ["MongoDB.pptx"], [], "plantilla"),
    ("s12-elasticsearch", "2027-01-18", "Elasticsearch", ["RA4 c", "RA4 d", "RA5 c", "RA5 d"],
     "Índexs, mappings, Query DSL, agregacions i API _bulk. Demo: NiFi vs Logstash vs Filebeat.",
     "Indexar un CSV amb _bulk i fer cerques de text complet.",
     [("Elastic · Introducción", "elastic/elastic_intro/"), ("Elastic · Operaciones", "elastic/elastic_ops/")],
     ["Elasticsearch.pptx", "Explorar Elasticsearch.docx", "Pràctica ElasticSearch.docx", "CheatSheet ElasticSearch.docx"], [], "plantilla"),
    ("s13-nosql-seguretat", "2027-01-25", "Seguretat i paral·lelisme NoSQL", ["RA4 e", "RA5 e", "RA5 f"],
     "Seguretat en Elastic (xpack, rols, API keys) i en MongoDB (autenticació, rols). Shards, rèpliques i _bulk en paral·lel. Prova RA4 + RA5.",
     "Crear rols de només lectura i mesurar càrregues paral·leles.",
     [("Elastic · Ampliación", "elastic/ampliacion/")], [], ["Guió de seguretat NoSQL"], "plantilla"),
    ("s14-kibana", "2027-02-01", "Kibana", ["Ampliació"],
     "Data views, Lens i dashboards.", "Dashboard sobre un índex propi.",
     [("Kibana", "elastic/kibana/"), ("Caso de uso", "elastic/caso_uso/"), ("Dashboards Covid", "elastic/dashboards/")], [], [], "plantilla"),
    ("s15-powerbi", "2027-02-08", "Power BI", ["Ampliació"],
     "Power BI connectat a dw_compras: Import vs DirectQuery, model estrella i mesures.", "Informe de compres.",
     [], ["Power BI ( Jorge ).pptx", "Power BI.pptx", "BigData - Power BI.pdf", "Visualitzacions.pptx"], [], "plantilla"),
    ("s16-prova", "2027-02-15", "Prova final", ["RA1", "RA2 c-e", "RA3", "RA4", "RA5"],
     "Prova pràctica final de la part de Prof. 1.", "", [], [], ["Enunciat i rúbrica"], "plantilla"),
]

P2 = [
    ("d01-nifi-intro", "2026-10-07", "NiFi: arquitectura i instal·lació", ["RA6 a", "RA6 b"],
     "Què és NiFi, arquitectura (FlowFile, Processor, Connection, repositoris), interfície i instal·lació de NiFi 2.x amb Docker (HTTPS 8443).",
     "Instal·lar NiFi i entrar a la interfície.",
     [("Introducción", "nifi/introduccion_nifi/"), ("Arquitectura", "nifi/arquitectura/"), ("Interfaz gráfica", "nifi/interfaz/"), ("Instalación y despliegue", "nifi/instalacion/")],
     ["NiFi.pptx (cal passar-lo a NiFi 2.x)"], [], "plantilla"),
    ("d02-nifi-flowfiles", "2026-10-14", "NiFi: primer flux i FlowFiles", ["RA6 a", "RA7 a", "RA7 b"],
     "Primer flux GetFile → PutFile. FlowFiles: atributs i contingut.", "Moure fitxers d'un origen a un destí.",
     [("Primer flujo de datos", "nifi/primerflujo/"), ("Flowfiles", "nifi/flowfiles/")],
     ["BigData - NiFi - Práctica 1", "BigData - NiFi - Práctica 2"], [], "plantilla"),
    ("d03-nifi-processors", "2026-10-21", "NiFi: processors i connexions", ["RA6 d"],
     "Processors i Expression Language, enrutament. Connections: backpressure i prioritzadors. Process groups i funnels.",
     "Filtrar i enrutar fitxers segons els atributs i el contingut.",
     [("Processors", "nifi/processors/"), ("Connections", "nifi/connections/")],
     ["BigData - NiFi - Práctica 3", "BigData - NiFi - Práctica 4", "BigData - NiFi - Práctica 6"], [], "plantilla"),
    ("d04-nifi-controllers", "2026-10-28", "NiFi: controller services i records", ["RA6 c", "RA6 d", "RA7 c"],
     "Controller Services: Record Readers i Writers. ConvertRecord (CSV ↔ JSON ↔ XML) i QueryRecord. Parameter Contexts.",
     "Convertir formats i fer consultes SQL sobre records.",
     [("Controllers · Introducción", "nifi/controllers/01-introduccion/"), ("Controllers · Configuración", "nifi/controllers/02-configuracion/"), ("Controllers · Servicios", "nifi/controllers/03-principales-controller-services/")],
     ["BigData - NiFi - Práctica 7", "P10. Transformant dades amb Nifi"], [], "plantilla"),
    ("d05-json-xml", "2026-11-04", "JSON i XML a fons", ["RA6 c", "RA6 d"],
     "Aplanament de JSON (JoltTransformJSON, FlattenJson), XPath, XSLT i validació amb JSON Schema i XSD. Lectura amb Python des de NiFi.",
     "Aplanar estructures niades i validar-les.", [], [], ["Material nou"], "plantilla"),
    ("d06-fitxers-escriptura", "2026-11-11", "Escriure i modificar fitxers", ["RA7 c", "RA7 d"],
     "Generar, modificar i esborrar registres en fitxers (UpdateRecord, QueryRecord, PartitionRecord, MergeRecord) i amb un script Python.",
     "Mantindre un fitxer mestre actualitzat.", [], [], ["Material nou"], "plantilla"),
    ("d07-nifi-bd", "2026-11-18", "NiFi i bases de dades", ["RA2 a", "RA2 b"],
     "DBCPConnectionPool amb PostgreSQL local i al núvol. ExecuteSQLRecord i QueryDatabaseTable incremental sobre l'OLTP de compres.",
     "Extracció incremental de l'OLTP.",
     [("Controllers · Arquitecturas", "nifi/controllers/04-arquitecturas/"), ("Casos de uso (Lab 1)", "nifi/casos_de_uso/")],
     ["nifiCasoUsoPostgreSQL", "PostgreSQL per a Big Data.docx", "P11. Cas d'ús ETL amb NiFi"], [], "plantilla"),
    ("d08-multifont", "2026-11-25", "Diverses fonts alhora", ["RA2 f"],
     "Diverses fonts i destins alhora (PostgreSQL, CSV i API), LookupRecord i taules intermèdies. Demo d'ODI.",
     "Pipeline amb enriquiment i staging.", [], ["P12. el-tiempo.net", "Oracle Data Integrator.pptx"], [], "plantilla"),
    ("d09-api-rest", "2026-12-02", "API REST", ["RA8 a", "RA8 b"],
     "InvokeHTTP, paginació, límits de peticions, reintents i Jolt. Open-Meteo, el-tiempo.net i Open Data GVA.",
     "Ingesta periòdica d'una API.", [], ["nifiCasoUsoAPI", "nifiCasoUsoMeteo", "Consulta d'una API amb Nifi.docx", "Exercici de consulta d'una API.docx"], [], "plantilla"),
    ("d10-confidencialitat", "2026-12-09", "Confidencialitat", ["RA7 e"],
     "Xifratge (EncryptContentAge o EncryptContentPGP), hash i pseudonimització, RGPD i provenance. Lliurament RA6 + RA7.",
     "Pseudonimitzar dades personals en un pipeline.", [], [], ["Material nou"], "plantilla"),
    ("d11-hdfs", "2026-12-16", "HDFS", ["RA6 e", "RA7 f"],
     "Escriptura distribuïda des de NiFi (PutHDFS i FetchHDFS) i particionat.", "Bolcat de fitxers a HDFS i retorn.",
     [], ["nifiCasoUsoHadoop", "NiFi - Lectura fitxers filesystem i volcat a hdfs.docx", "Big Data Aplicat P1–P5"], [], "plantilla"),
    ("d12-iot", "2027-01-13", "IoT i sensòrica", ["RA8 e", "RA8 f", "RA1 b"],
     "Raspberry Pi → MQTT (Mosquitto) → NiFi ConsumeMQTT → filtratge → PostgreSQL o fitxer. Alternatives: OPC UA simulat o una opció combinada.",
     "Captura de la sensòrica del centre.", [], ["Big Data Aplicat · Azure, pràctiques 2.1–2.4"], ["Material nou"], "plantilla"),
    ("d13-nifi-nosql", "2027-01-20", "NiFi cap a NoSQL", ["RA5 a", "RA4 a"],
     "PutMongoRecord i PutElasticsearchRecord, amb càrrega periòdica.", "Open-Meteo → MongoDB i Elasticsearch.",
     [("Casos de uso (Lab 2)", "nifi/casos_de_uso/")], ["nifiCasoUsoMongoDB"], [], "plantilla"),
    ("d14-sparql", "2027-01-27", "Web semàntica i SPARQL", ["RA8 c", "RA8 d"],
     "RDF, OWL, SPARQL a Wikidata o DBpedia amb filtres en origen, des de NiFi i des de Python.", "Consultes SPARQL exportades a CSV.",
     [], [], ["Material nou"], "plantilla"),
    ("d15-spark", "2027-02-03", "Spark", ["RA2 g", "RA6 e", "RA7 f", "RA8 g"],
     "PySpark: lectura JDBC particionada, CSV i JSON en paral·lel, Parquet particionat, WordCount o logs.",
     "Pipeline paral·lel sobre compres.", [], ["Big Data Aplicat: 6. SPARK, P14, P15"], [], "plantilla"),
    ("d16-integracio", "2027-02-10", "Integració i governança", ["RA6 a", "RA7 a"],
     "Pipeline extrem a extrem: Parameter Contexts, NiFi Registry, tolerància a fallades i backpressure. Lliurament RA8.",
     "Pipeline complet versionat.", [("Controllers · Arquitecturas", "nifi/controllers/04-arquitecturas/")], [], [], "plantilla"),
    ("d17-prova", "2027-02-17", "Prova final", ["RA2 a,b,f,g", "RA6", "RA7", "RA8"],
     "Prova pràctica final de la part de Prof. 2.", "", [], [], ["Enunciat i rúbrica"], "plantilla"),
]

FESTIUS = [
    ("2026-10-12", "Festa Nacional d'Espanya"),
    ("2026-12-07", "Pont de la Constitució"),
    ("2026-12-23", "Vacances de Nadal"),
    ("2026-12-28", "Vacances de Nadal"),
    ("2026-12-30", "Vacances de Nadal"),
    ("2027-01-04", "Vacances de Nadal"),
    ("2027-01-06", "Reis"),
]
